config/routes.rb
Rails.application.routes.draw do

  get 'pdfs/index'

  root 'pdfs#index'

  resources :pdfs

  get 'pdfs/fullbook.pdf', to: 'pdfs#fullbook', as: 'fullbook'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController

  def index
  end

  def new
    temp_file = "#{::Rails.root}/public/mlhpdf"       
    Prawn::Document.generate("whatever.pdf", :skip_page_creation => true) do |f|
      f.start_new_page(:template => temp_file, :template_page => 1)
      send_data f.render,disposition:"inline"
    end	
  end   

  def fullbook
    temp_file = "#{::Rails.root}/public/mlhpdf"       
    Prawn::Document.generate("whatever.pdf", :template => temp_file) do |f|
      send_data f.render,disposition:"inline"
    end	
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdftest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pdfs/index.html.erb
<h1>Pdfs#index</h1>
<p>Find me in app/views/pdfs/index.html.erb</p>
<%= link_to "Preview", new_pdf_path(format: "pdf") %> | <%= link_to "Full book", fullbook_path(format: "pdf")%>

app/views/pdfs/new.html.erb
<h1>PDF generation sucks</h1>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>